//! Integration test comparing rabbit's `glm52::convert::shard::convert_shard` against colibrì's
//! REAL `convert_fp8_to_int4.py` (vendored verbatim, not reimplemented) run on the exact same
//! synthetic FP8 source shard — byte-for-byte, both in the default per-row quantization mode
//! and in grouped (`--group-size`) mode.
//!
//! Needs `tests/oracle/convert_src/` + `tests/oracle/convert_ref_row/` +
//! `tests/oracle/convert_ref_grouped/`, generated by `tests/oracle/make_convert_oracle.py`
//! (needs `torch`/`safetensors` — dev-time only, see that script's own doc for the Docker
//! invocation). Skips (not fails) when the fixtures are absent, same policy as
//! `teacher_forcing.rs`/`teacher_forcing_kimi.rs`.

use rabbit::glm52::convert::shard::{convert_shard, glm_classifier, BitsMap, ConvertOpts};
use rabbit::glm52::convert::writer::OutTensor;
use rabbit::safetensors::{DType, Shards};
use std::path::Path;

fn oracle_root() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oracle")
}

fn base_opts(group_size: usize) -> ConvertOpts {
    ConvertOpts { n_layers: 1, ebits: 4, io_bits: 8, xbits: 4, keep_mtp: false, keep_idx: false, group_size, bits_map: BitsMap::default(), overrides: vec![] }
}

/// Runs rabbit's converter on `tests/oracle/convert_src`, loads `ref_dir`'s reference output,
/// and asserts every tensor matches: same set of names, same dtype, same shape, same raw bytes.
fn assert_matches_reference(group_size: usize, ref_dir: &Path) {
    let src = oracle_root().join("convert_src");
    let got = convert_shard(&src, &base_opts(group_size), glm_classifier(&base_opts(group_size)), None).expect("convert_shard failed");

    let reference = Shards::open(ref_dir).expect("failed to open the reference output dir");
    let ref_names: std::collections::BTreeSet<String> = reference.tensors().iter().map(|t| t.name.clone()).collect();
    let got_names: std::collections::BTreeSet<String> = got.keys().cloned().collect();
    assert_eq!(got_names, ref_names, "tensor name set differs from the Python reference");

    for t in reference.tensors() {
        let out = got.get(&t.name).unwrap_or_else(|| panic!("rabbit's output is missing {}", t.name));
        match (t.dtype, out) {
            (DType::F32, OutTensor::F32 { shape, data }) => {
                assert_eq!(shape, &t.shape, "{}: shape differs from the Python reference", t.name);
                let want = reference.read_f32(&t.name, false).unwrap();
                assert_eq!(data, &want, "{}: F32 bytes differ from the Python reference", t.name);
            }
            (DType::U8, OutTensor::U8 { shape, data }) => {
                assert_eq!(shape, &t.shape, "{}: shape differs from the Python reference", t.name);
                let want = reference.read_raw(&t.name, false).unwrap();
                assert_eq!(data, &want, "{}: U8 bytes differ from the Python reference", t.name);
            }
            (dt, out) => {
                let got_kind = match out {
                    OutTensor::F32 { .. } => "F32",
                    OutTensor::U8 { .. } => "U8",
                };
                panic!("{}: dtype/variant mismatch — reference dtype {dt:?}, rabbit produced {got_kind}", t.name);
            }
        }
    }
}

#[test]
fn matches_the_real_colibri_converter_per_row() {
    let ref_dir = oracle_root().join("convert_ref_row");
    if !oracle_root().join("convert_src").is_dir() || !ref_dir.is_dir() {
        eprintln!("skipping: run tests/oracle/make_convert_oracle.py first (see its own doc)");
        return;
    }
    assert_matches_reference(0, &ref_dir);
}

#[test]
fn matches_the_real_colibri_converter_grouped() {
    let ref_dir = oracle_root().join("convert_ref_grouped");
    if !oracle_root().join("convert_src").is_dir() || !ref_dir.is_dir() {
        eprintln!("skipping: run tests/oracle/make_convert_oracle.py first (see its own doc)");
        return;
    }
    assert_matches_reference(2, &ref_dir);
}
