//! Integration tests against the tiny GLM-5.2 oracle, matching colibri's own self-test
//! criteria (`setup.sh`'s "32/32 posizioni" teacher-forcing check and its greedy-replay
//! check): a single forward pass over `full_ids` must reproduce the reference's per-position
//! argmax exactly, AND incremental greedy decode from `prompt_ids` must reproduce
//! `full_ids[len(prompt_ids):]` exactly — the former validates prefill, the latter validates
//! the KV-cache-across-calls decode path teacher-forcing alone can't exercise.
//!
//! Needs `tests/oracle/glm_tiny/` + `tests/oracle/ref_glm.json`, generated by
//! `tests/oracle/make_glm_oracle.py` (requires `torch`/`transformers`/`safetensors` — a
//! dev-time-only dependency, never a runtime one, per `rabbit-plan.md`). Both tests skip (not
//! fail) when the fixture is absent, same policy as the tokenizer fixture in `tools/`.

use rabbit::generate::{self, ExpertCaches, KvState, Rng, SamplingConfig};
use rabbit::model::Model;
use rabbit::safetensors::Shards;
use std::path::Path;

struct Oracle {
    prompt_ids: Vec<usize>,
    full_ids: Vec<usize>,
    tf_pred: Vec<usize>,
    model: Model,
    shards: Shards,
}

/// Loads the fixture, or returns `None` (callers print a skip message) if it's absent.
fn load_oracle() -> Option<Oracle> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oracle");
    let glm_tiny = root.join("glm_tiny");
    let ref_path = root.join("ref_glm.json");
    if !glm_tiny.is_dir() || !ref_path.is_file() {
        return None;
    }

    let reference: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&ref_path).unwrap()).unwrap();
    let as_usize_vec = |key: &str| -> Vec<usize> {
        reference[key]
            .as_array()
            .unwrap_or_else(|| panic!("ref_glm.json: missing {key}"))
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect()
    };
    let prompt_ids = as_usize_vec("prompt_ids");
    let full_ids = as_usize_vec("full_ids");
    let tf_pred = as_usize_vec("tf_pred");
    assert_eq!(full_ids.len(), tf_pred.len(), "ref_glm.json: full_ids/tf_pred length mismatch");

    // dbits=ebits=16: colibri's own self-test (setup.sh: `./glm 64 16 16`) uses bits>=16,
    // which lands in QT's F32 passthrough format — exact, no quantization noise. Anything
    // less would risk flipping an argmax on this tiny random model purely from quantization
    // error, which is not what these tests are meant to catch.
    let model = Model::load(&glm_tiny, 16, 16).expect("failed to load tests/oracle/glm_tiny");
    let shards = Shards::open(&glm_tiny).unwrap();
    Some(Oracle { prompt_ids, full_ids, tf_pred, model, shards })
}

fn skip(test_name: &str) {
    eprintln!(
        "SKIP {test_name}: tests/oracle/glm_tiny not found — run \
         `cd tests/oracle && python3 make_glm_oracle.py` first (needs torch/transformers/safetensors)."
    );
}

#[test]
fn teacher_forcing_matches_oracle_at_every_position() {
    let Some(o) = load_oracle() else {
        skip("teacher_forcing_matches_oracle_at_every_position");
        return;
    };

    // capacity = n_experts -> every routed expert fits, so this run never evicts (matches
    // the plan's expectation that the tiny oracle's experts all stay resident).
    let mut caches = ExpertCaches::new(&o.model, o.model.cfg.n_experts as usize);
    let mut kv = KvState::new(&o.model);

    let logits = generate::step_all(&o.model, &o.shards, &mut caches, &mut kv, &o.full_ids, 0).expect("forward pass failed");
    let v = o.model.cfg.vocab as usize;

    let mut mismatches = Vec::new();
    for (i, chunk) in logits.chunks(v).enumerate() {
        let pred = generate::argmax(chunk);
        if pred != o.tf_pred[i] {
            mismatches.push((i, o.tf_pred[i], pred));
        }
    }

    let correct = o.tf_pred.len() - mismatches.len();
    assert!(
        mismatches.is_empty(),
        "{correct}/{} positions matched; mismatches (pos, expected, got): {mismatches:?}",
        o.tf_pred.len()
    );
    eprintln!("teacher-forcing: {correct}/{} positions matched", o.tf_pred.len());
}

#[test]
fn greedy_generation_from_prompt_reproduces_the_oracle_continuation() {
    let Some(o) = load_oracle() else {
        skip("greedy_generation_from_prompt_reproduces_the_oracle_continuation");
        return;
    };

    let mut caches = ExpertCaches::new(&o.model, o.model.cfg.n_experts as usize);
    let mut kv = KvState::new(&o.model);
    let mut rng = Rng::default(); // unused at temperature<=0, but required by the API
    let n_new = o.full_ids.len() - o.prompt_ids.len();

    let generated = generate::generate(&o.model, &o.shards, &mut caches, &mut kv, &o.prompt_ids, n_new, &SamplingConfig::greedy(), &mut rng, &[])
        .expect("generation failed");

    let expected = &o.full_ids[o.prompt_ids.len()..];
    assert_eq!(generated, expected, "greedy continuation diverged from the oracle's full_ids tail");
    eprintln!("greedy decode: {}/{} tokens matched the oracle continuation", generated.len(), expected.len());
}
