//! Integration tests against the tiny Kimi Linear oracle — the sibling of `teacher_forcing.rs`'s
//! GLM-5.2 version, same two criteria: a single forward pass over `full_ids` must reproduce the
//! reference's per-position argmax exactly (validates prefill/KDA-state-from-scratch), AND
//! incremental greedy decode from `prompt_ids` must reproduce `full_ids[len(prompt_ids):]`
//! exactly (validates the KDA-recurrent-state/KV-cache-across-calls decode path).
//!
//! Needs `tests/oracle/kimi_tiny/` + `tests/oracle/ref_kimi.json`, generated by
//! `tests/oracle/make_kimi_oracle.py` (requires `torch`/`transformers`/`einops`/`fla-core`/
//! `safetensors` in a Python environment — see that script's own doc for the Docker-based setup
//! this host needs, and why it monkeypatches `fla`'s Triton-only kernels). Skips (not fails)
//! when the fixture is absent, same policy as `teacher_forcing.rs`.
//!
//! Unlike `teacher_forcing.rs`, the oracle's own `full_ids` was generated via a full-recompute
//! greedy loop (no KV cache) rather than `model.generate()` — the patched CPU kernels in
//! `make_kimi_oracle.py` only implement the no-cache path. This doesn't weaken the incremental-
//! decode test below: KDA's recurrence and MLA's attention are exact recomputations either way
//! (no algorithmic difference between "cached" and "just recomputed" — the result depends only
//! on final K/V/state content, never on when it was computed), so rabbit's own incremental
//! `step`-based decode is expected to reproduce the same continuation bit-for-bit.

use rabbit::generate::argmax;
use rabbit::kimi_linear::generate::{self as kgen, ExpertCaches, KvState};
use rabbit::kimi_linear::model::Model;
use rabbit::safetensors::Shards;
use std::path::Path;

struct Oracle {
    prompt_ids: Vec<usize>,
    full_ids: Vec<usize>,
    tf_pred: Vec<usize>,
    model: Model,
    shards: Shards,
}

fn load_oracle() -> Option<Oracle> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oracle");
    let kimi_tiny = root.join("kimi_tiny");
    let ref_path = root.join("ref_kimi.json");
    if !kimi_tiny.is_dir() || !ref_path.is_file() {
        return None;
    }

    let reference: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&ref_path).unwrap()).unwrap();
    let as_usize_vec = |key: &str| -> Vec<usize> {
        reference[key]
            .as_array()
            .unwrap_or_else(|| panic!("ref_kimi.json: missing {key}"))
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect()
    };
    let prompt_ids = as_usize_vec("prompt_ids");
    let full_ids = as_usize_vec("full_ids");
    let tf_pred = as_usize_vec("tf_pred");
    assert_eq!(full_ids.len(), tf_pred.len(), "ref_kimi.json: full_ids/tf_pred length mismatch");

    // dbits=ebits=16: F32 passthrough in QT, no quantization noise -- same reasoning as
    // teacher_forcing.rs's glm_tiny load (this tiny random model's argmax could otherwise flip
    // purely from quantization error, which isn't what this test means to catch).
    let model = Model::load(&kimi_tiny, 16, 16).expect("failed to load tests/oracle/kimi_tiny");
    let shards = Shards::open(&kimi_tiny).unwrap();
    Some(Oracle { prompt_ids, full_ids, tf_pred, model, shards })
}

fn skip(test_name: &str) {
    eprintln!(
        "SKIP {test_name}: tests/oracle/kimi_tiny not found — run \
         `cd tests/oracle && python3 make_kimi_oracle.py` (via Docker, see that script's doc) first."
    );
}

#[test]
fn teacher_forcing_matches_oracle_at_every_position() {
    let Some(o) = load_oracle() else {
        skip("teacher_forcing_matches_oracle_at_every_position");
        return;
    };

    let mut caches = ExpertCaches::new(&o.model, o.model.cfg.n_experts as usize);
    let mut kv = KvState::new(&o.model);

    let logits = kgen::step_all(&o.model, &o.shards, &mut caches, &mut kv, &o.full_ids, 0).expect("forward pass failed");
    let v = o.model.cfg.vocab as usize;

    let mut mismatches = Vec::new();
    for (i, chunk) in logits.chunks(v).enumerate() {
        let pred = argmax(chunk);
        if pred != o.tf_pred[i] {
            mismatches.push((i, o.tf_pred[i], pred));
        }
    }

    let correct = o.tf_pred.len() - mismatches.len();
    assert!(
        mismatches.is_empty(),
        "{correct}/{} positions matched; mismatches (pos, expected, got): {mismatches:?}",
        o.tf_pred.len()
    );
    eprintln!("teacher-forcing: {correct}/{} positions matched", o.tf_pred.len());
}

#[test]
fn greedy_generation_from_prompt_reproduces_the_oracle_continuation() {
    let Some(o) = load_oracle() else {
        skip("greedy_generation_from_prompt_reproduces_the_oracle_continuation");
        return;
    };

    let mut caches = ExpertCaches::new(&o.model, o.model.cfg.n_experts as usize);
    let mut kv = KvState::new(&o.model);

    let expected_continuation = &o.full_ids[o.prompt_ids.len()..];
    let mut logits = kgen::step(&o.model, &o.shards, &mut caches, &mut kv, &o.prompt_ids, 0).expect("prefill failed");
    let mut got = Vec::with_capacity(expected_continuation.len());

    for pos in o.prompt_ids.len()..(o.prompt_ids.len() + expected_continuation.len()) {
        let next = argmax(&logits);
        got.push(next);
        logits = kgen::step(&o.model, &o.shards, &mut caches, &mut kv, &[next], pos).expect("decode step failed");
    }

    assert_eq!(got, expected_continuation, "incremental greedy decode diverged from the oracle's continuation");
}
