//! Integration tests against the tiny Qwen 3.8 oracle — the sibling of `teacher_forcing_k3.rs`, with
//! the same two criteria:
//!
//! 1. **Teacher forcing**: one forward pass over `full_ids` must reproduce the reference's
//!    per-position argmax exactly. This is the test that catches what per-op unit tests structurally
//!    cannot — a wrong layer order, a residual added in the wrong place, the `(1 + w)` RMSNorm
//!    convention applied to the wrong norm, a swapped `in_proj_a`/`in_proj_b`, the query/gate split
//!    read as halves instead of per head. The oracle's config turns on every Qwen-specific path at
//!    once (3:1 GDN/GQA hybrid, `attn_output_gate`, partial RoPE, GQA in BOTH mixers, routed MoE plus
//!    a gated shared expert) and randomizes the norm weights away from zero on purpose — see
//!    `make_qwen38_oracle.py`.
//! 2. **Incremental decode**: greedy stepping from `prompt_ids` must reproduce
//!    `full_ids[prompt_ids.len()..]` exactly, which exercises the state-carried-across-calls paths
//!    (the GDN recurrence and the GQA KV cache) that a single batched forward never touches.
//!
//! Both are argmax comparisons rather than logit tolerances, matching the sibling tests: exact
//! agreement on the selected token is the criterion that stays meaningful once weights are quantized,
//! and the fixture is loaded at 32 bits (`QT::alloc`'s f32 tier) so nothing here is lossy anyway.
//!
//! Needs `tests/oracle/qwen38_tiny/` + `tests/oracle/ref_qwen38.json`, generated by
//! `tests/oracle/make_qwen38_oracle.py` (Docker-based, see that script's doc). Skips (not fails) when
//! the fixture is absent, same policy as every other oracle-backed test here.

use rabbit::generate::argmax;
use rabbit::qwen38::generate::{self as qgen, ExpertCaches, KvState};
use rabbit::qwen38::model::Model;
use rabbit::safetensors::Shards;
use std::path::Path;

struct Oracle {
    prompt_ids: Vec<usize>,
    full_ids: Vec<usize>,
    tf_pred: Vec<usize>,
    model: Model,
    shards: Shards,
}

fn load_oracle(what: &str) -> Option<Oracle> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oracle");
    let tiny = root.join("qwen38_tiny");
    let ref_path = root.join("ref_qwen38.json");
    if !tiny.is_dir() || !ref_path.is_file() {
        eprintln!(
            "SKIP {what}: {} / {} not found — run tests/oracle/make_qwen38_oracle.py first (see its docstring for the Docker one-liner).",
            tiny.display(),
            ref_path.display()
        );
        return None;
    }
    let refs: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&ref_path).unwrap()).unwrap();
    let ids = |key: &str| -> Vec<usize> {
        refs[key].as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as usize).collect()
    };
    // 32 bits keeps every weight in the f32 tier, so any mismatch is a logic difference rather than
    // quantization noise.
    let model = Model::load(&tiny, 32, 32).expect("the tiny oracle checkpoint must load");
    let shards = Shards::open(&tiny).expect("the tiny oracle shards must open");
    Some(Oracle { prompt_ids: ids("prompt_ids"), full_ids: ids("full_ids"), tf_pred: ids("tf_pred"), model, shards })
}

#[test]
fn teacher_forced_argmax_matches_the_reference_at_every_position() {
    let Some(o) = load_oracle("teacher_forced_argmax_matches_the_reference_at_every_position") else { return };
    let vocab = o.model.cfg.vocab as usize;

    let mut caches = ExpertCaches::new(&o.model, o.model.cfg.n_experts as usize);
    let mut kv = KvState::new(&o.model);
    let logits = qgen::step_all(&o.model, &o.shards, &mut caches, &mut kv, &o.full_ids, 0).unwrap();
    assert_eq!(logits.len(), o.full_ids.len() * vocab);

    let got: Vec<usize> = (0..o.full_ids.len()).map(|si| argmax(&logits[si * vocab..(si + 1) * vocab])).collect();
    let matches = got.iter().zip(&o.tf_pred).filter(|(a, b)| a == b).count();
    assert_eq!(
        got, o.tf_pred,
        "teacher-forced argmax mismatch ({matches}/{} positions agree)",
        o.tf_pred.len()
    );
}

#[test]
fn incremental_greedy_decode_reproduces_the_reference_continuation() {
    let Some(o) = load_oracle("incremental_greedy_decode_reproduces_the_reference_continuation") else { return };
    let expected = &o.full_ids[o.prompt_ids.len()..];

    let mut caches = ExpertCaches::new(&o.model, o.model.cfg.n_experts as usize);
    let mut kv = KvState::new(&o.model);
    let mut logits = qgen::step(&o.model, &o.shards, &mut caches, &mut kv, &o.prompt_ids, 0).unwrap();

    let mut produced = Vec::with_capacity(expected.len());
    for (i, _) in expected.iter().enumerate() {
        let next = argmax(&logits);
        produced.push(next);
        let pos = o.prompt_ids.len() + i;
        logits = qgen::step(&o.model, &o.shards, &mut caches, &mut kv, &[next], pos).unwrap();
    }
    assert_eq!(produced, expected, "incremental decode diverged from the reference continuation");
}

/// Prefill in one call and prefill token-by-token must reach the same state, against the ORACLE's
/// weights rather than the synthetic fixture `qwen38::generate`'s own unit test uses — a different
/// (real-shaped, randomized) weight set exercising the same invariant.
#[test]
fn batched_and_incremental_prefill_agree_on_the_oracle_weights() {
    let Some(o) = load_oracle("batched_and_incremental_prefill_agree_on_the_oracle_weights") else { return };

    let mut caches = ExpertCaches::new(&o.model, o.model.cfg.n_experts as usize);
    let mut kv_batched = KvState::new(&o.model);
    let batched = qgen::step(&o.model, &o.shards, &mut caches, &mut kv_batched, &o.prompt_ids, 0).unwrap();

    let mut kv_seq = KvState::new(&o.model);
    let mut incremental = Vec::new();
    for (i, &tok) in o.prompt_ids.iter().enumerate() {
        incremental = qgen::step(&o.model, &o.shards, &mut caches, &mut kv_seq, &[tok], i).unwrap();
    }
    assert_eq!(argmax(&batched), argmax(&incremental), "the two prefill paths must select the same token");
    for (i, (a, b)) in batched.iter().zip(&incremental).enumerate() {
        assert!((a - b).abs() < 1e-3, "logit {i}: batched {a} vs incremental {b}");
    }
}
