//! Integration tests against the tiny Kimi K3 oracle — the sibling of
//! `teacher_forcing_kimi.rs`'s Kimi Linear 48B version, same two criteria: a single forward pass
//! over `full_ids` must reproduce the reference's per-position argmax exactly (validates
//! prefill/KDA-state-from-scratch, including K3's own additions: SituAndMul, Stable LatentMoE,
//! Attention Residuals, the MLA output gate, and KDA's full-rank output gate + bounded decay
//! gate — the tiny oracle's config turns EVERY K3-only field on at once, see
//! `make_k3_oracle.py`), AND incremental greedy decode from `prompt_ids` must reproduce
//! `full_ids[len(prompt_ids):]` exactly (validates the KDA-recurrent-state/KV-cache-across-calls
//! decode path, unaffected by Attention Residuals since that's purely transient per forward call
//! — see `kimi_k3::attn_res`'s doc).
//!
//! Needs `tests/oracle/k3_tiny/` + `tests/oracle/ref_k3.json`, generated by
//! `tests/oracle/make_k3_oracle.py` (Docker-based setup, see that script's own doc). Skips (not
//! fails) when the fixture is absent, same policy as `teacher_forcing.rs`/`teacher_forcing_kimi.rs`.
//!
//! Same reasoning as `teacher_forcing_kimi.rs` for why incremental decode is expected to match a
//! no-KV-cache-generated `full_ids` bit-for-bit: KDA's recurrence and MLA's attention are exact
//! recomputations either way, and Attention Residuals only depends on the CURRENT forward call's
//! own layer sequence, never on prior calls.

use rabbit::generate::argmax;
use rabbit::kimi_k3::generate::{self as kgen, ExpertCaches, KvState};
use rabbit::kimi_k3::model::Model;
use rabbit::safetensors::Shards;
use std::path::Path;

struct Oracle {
    prompt_ids: Vec<usize>,
    full_ids: Vec<usize>,
    tf_pred: Vec<usize>,
    model: Model,
    shards: Shards,
}

fn load_oracle() -> Option<Oracle> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oracle");
    let k3_tiny = root.join("k3_tiny");
    let ref_path = root.join("ref_k3.json");
    if !k3_tiny.is_dir() || !ref_path.is_file() {
        return None;
    }

    let reference: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&ref_path).unwrap()).unwrap();
    let as_usize_vec = |key: &str| -> Vec<usize> {
        reference[key]
            .as_array()
            .unwrap_or_else(|| panic!("ref_k3.json: missing {key}"))
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect()
    };
    let prompt_ids = as_usize_vec("prompt_ids");
    let full_ids = as_usize_vec("full_ids");
    let tf_pred = as_usize_vec("tf_pred");
    assert_eq!(full_ids.len(), tf_pred.len(), "ref_k3.json: full_ids/tf_pred length mismatch");

    // dbits=ebits=16: F32 passthrough in QT, no quantization noise -- same reasoning as
    // teacher_forcing_kimi.rs's kimi_tiny load (this tiny random model's argmax could otherwise
    // flip purely from quantization error, which isn't what this test means to catch).
    let model = Model::load(&k3_tiny, 16, 16).expect("failed to load tests/oracle/k3_tiny");
    let shards = Shards::open(&k3_tiny).unwrap();
    Some(Oracle { prompt_ids, full_ids, tf_pred, model, shards })
}

fn skip(test_name: &str) {
    eprintln!(
        "SKIP {test_name}: tests/oracle/k3_tiny not found — run \
         `cd tests/oracle && python3 make_k3_oracle.py` (via Docker, see that script's doc) first."
    );
}

#[test]
fn teacher_forcing_matches_oracle_at_every_position() {
    let Some(o) = load_oracle() else {
        skip("teacher_forcing_matches_oracle_at_every_position");
        return;
    };

    let mut caches = ExpertCaches::new(&o.model, o.model.cfg.base.n_experts as usize);
    let mut kv = KvState::new(&o.model);

    let logits = kgen::step_all(&o.model, &o.shards, &mut caches, &mut kv, &o.full_ids, 0).expect("forward pass failed");
    let v = o.model.cfg.base.vocab as usize;

    let mut mismatches = Vec::new();
    for (i, chunk) in logits.chunks(v).enumerate() {
        let pred = argmax(chunk);
        if pred != o.tf_pred[i] {
            mismatches.push((i, o.tf_pred[i], pred));
        }
    }

    let correct = o.tf_pred.len() - mismatches.len();
    assert!(
        mismatches.is_empty(),
        "{correct}/{} positions matched; mismatches (pos, expected, got): {mismatches:?}",
        o.tf_pred.len()
    );
    eprintln!("teacher-forcing: {correct}/{} positions matched", o.tf_pred.len());
}

#[test]
fn greedy_generation_from_prompt_reproduces_the_oracle_continuation() {
    let Some(o) = load_oracle() else {
        skip("greedy_generation_from_prompt_reproduces_the_oracle_continuation");
        return;
    };

    let mut caches = ExpertCaches::new(&o.model, o.model.cfg.base.n_experts as usize);
    let mut kv = KvState::new(&o.model);

    let expected_continuation = &o.full_ids[o.prompt_ids.len()..];
    let mut logits = kgen::step(&o.model, &o.shards, &mut caches, &mut kv, &o.prompt_ids, 0).expect("prefill failed");
    let mut got = Vec::with_capacity(expected_continuation.len());

    for pos in o.prompt_ids.len()..(o.prompt_ids.len() + expected_continuation.len()) {
        let next = argmax(&logits);
        got.push(next);
        logits = kgen::step(&o.model, &o.shards, &mut caches, &mut kv, &[next], pos).expect("decode step failed");
    }

    assert_eq!(got, expected_continuation, "incremental greedy decode diverged from the oracle's continuation");
}
